#!/usr/bin/env ruby

require "bundler/setup"
require "callstacking/rails"

include Callstacking::Rails::Settings

action = ARGV[0]&.downcase&.strip

if action.nil?
  Callstacking::Rails::Setup.instructions
  exit!(1)
end

read_settings

case action
  when 'register'
    `open #{settings.url || Callstacking::Rails::Settings::PRODUCTION_URL}/users/sign_up`

  when 'setup'
    Callstacking::Rails::Setup.new.start
end
