#!/usr/bin/env ruby

require "bundler/setup"
require "callstacking/rails"

action = Callstacking::Rails::Cli.action(ARGV)
settings = Callstacking::Rails::Settings.new

if action.nil?
  Callstacking::Rails::Setup.instructions
  exit!(1)
end

cli = Callstacking::Rails::Cli.new(action, settings)
cli.run