#!/usr/bin/env ruby

require "bundler/setup"
require "callstacking/rails/setup"
require "callstacking/rails/settings"

include Callstacking::Rails::Settings

action = ARGV[0]&.downcase&.strip

if action.nil?
  Callstacking::Rails::Setup.instructions
  exit!(1)
end

read_settings

case action
  when 'register'
    `open #{settings[:url] || Callstacking::Rails::Settings::PRODUCTION_URL}/users/sign_up`

  when 'setup'
    Callstacking::Rails::Setup.new.start

  when 'enable'
    Callstacking::Rails::Setup.new.enable_disable
    puts "Call Stacking tracing enabled (#{Callstacking::Rails::Env.environment})"

  when 'disable'
    Callstacking::Rails::Setup.new.enable_disable(enabled: false)
    puts "Call Stacking tracing disabled (#{Callstacking::Rails::Env.environment})"
end
